# Generated by Django 4.2 on 2026-03-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SolarReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('panel_id', models.CharField(max_length=50)),
                ('voltage', models.FloatField()),
                ('current', models.FloatField()),
                ('temperature', models.FloatField()),
                ('light_intensity', models.IntegerField()),
                ('humidity', models.FloatField()),
                ('power_watt', models.FloatField()),
                ('local_alert', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
