# Generated by Django 4.2 on 2026-03-11 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='solarreading',
            name='cloud_processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='solarreading',
            name='humidity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='solarreading',
            name='light_intensity',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='solarreading',
            name='panel_id',
            field=models.CharField(max_length=100),
        ),
    ]
